# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
development:
  adapter: mysql
  encoding: utf-8
  database: crazytour
  pool: 5
  username: root
  password: webonise6186
  socket: 
